---
image:
  name: docker:18.03

services:
  - docker:dind

before_script:
  - apk add --virtual .build-deps libffi-dev openssl-dev gcc linux-headers musl-dev
  - apk add git bash make python3-dev chromium-chromedriver chromium
  - pip3 install pipenv selenium docker-compose
  - pipenv install --skip-lock --three openwisp_utils[qa]
  # configure box
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token $CI_REGISTRY --password-stdin
  - export hosts="127.0.0.1 dashboard.openwisp.org controller.openwisp.org
                            radius.openwisp.org topology.openwisp.org"
  - echo "${hosts}" >> /etc/hosts

build:
  script:
      - pipenv run openwisp-qa-check --skip-checkmigrations
      - make publish USER=$CI_REGISTRY TAG=edge
