---
# Pass environment variables only to the postgresql container.
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: openwisp-postgres
data:
  # If you change any value here, remember to change the values
  # of common-config `DB_NAME`, `DB_USER` & `DB_PASS` as well.
  POSTGRES_DB: openwisp_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
# Pass the environment variables to all the openwisp containers.
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  DJANGO_SECRET_KEY: MY_COMPANY_SECRET_KEY
  DASHBOARD_DOMAIN: dashboard.openwisp.org
  API_DOMAIN: api.openwisp.org
  RADIUS_DOMAIN: radius.openwisp.org
  VPN_DOMAIN: openvpn.openwisp.org
  DASHBOARD_INTERNAL: dashboard-internal
  API_INTERNAL: api-internal
  RADIUS_INTERNAL: radius-internal
  NGINX_SERVER_NAME_HASH_BUCKET: "64"
  SSL_CERT_MODE: "External"
  DEBUG_MODE: "False"
  TZ: "Asia/Kolkata"
  POSTFIX_RELAYHOST: "[smtp.gmail.com]:587"
  POSTFIX_ALLOWED_SENDER_DOMAINS: "openwisp.org gmail.com"
  POSTFIX_MYNETWORKS: "10.0.0.0/8"
  DJANGO_FREERADIUS_ALLOWED_HOSTS: "10.0.0.0/8"
  POSTFIX_RELAYHOST_USERNAME: "example@gmail.com"
  POSTFIX_RELAYHOST_PASSWORD: "example"
  DB_NAME: openwisp_db
  DB_USER: admin
  DB_PASS: admin
---
# Pass the environment variables to nfs-server
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-config
data:
  EXPORT_DIR: "/exports"
  EXPORT_OPTS: "*(rw,fsid=0,insecure,no_root_squash,no_subtree_check,sync)"
