#!/bin/bash

if [ ! -f ".env" ]; then
   echo ".env file does not exist. Please create .env file containing the variables."
   exit
fi

CREATE=false
FILE=${1}

if [ $1 ] && [ $1 == "--create" ]; then
   CREATE=true
   FILE=${2}
elif [ $2 ] &&  [ $2 == '--create' ]; then
   CREATE=true
fi

if [ ! $FILE ]; then
   echo "Please Provide a file"
   exit
fi

if [ ! -f $FILE ]; then
   echo "File $FILE does not exist"
   exit
fi


COM="cat $FILE | sed \""

for var in $(cat .env); do
   COM="$COM;s/{{${var/=/\}\}/}/g"
done

if $CREATE; then
   COM="$COM\" | kubectl create -f -"
else
   COM="$COM\" | kubectl apply -f -"
fi

eval "$COM"
