---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: openwisp-postgres
data:
  POSTGRES_DB: openwisp_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  DJANGO_SECRET_KEY: MY_COMPANY_SECRET_KEY
  DASHBOARD_DOMAIN: DASHBOARD_DOMAIN
  CONTROLLER_DOMAIN: CONTROLLER_DOMAIN
  RADIUS_DOMAIN: RADIUS_DOMAIN
  TOPOLOGY_DOMAIN: TOPOLOGY_DOMAIN
  NGINX_SERVER_NAME_HASH_BUCKET: "64"
  SSL_CERT_MODE: "False"
  DJANGO_DEFAULT_FROM_EMAIL: postmaster@example.com
  POSTFIX_MYNETWORKS: 10.0.0.0/8
  DEBUG_MODE: "True"
